env:
    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "CustomRom Build"
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 8
      memory: 32G

  Clone_script:
      - repo init -u https://github.com/LineageOS/android.git -b lineage-20.0
      - git clone https://github.com/U89-sk/device_realme_RMX1851 -b lineage-20.0 device/realme/RMX1851
      - git clone https://github.com/U89-sk/android_vendor_RMX1851 vendor/realme/RMX1851
      - git clone https://github.com/viviz-kernel-Devices/viviz-sdm710 kernel/realme/sdm710
      - repo sync -j$(nproc) --force-sync --no-clone-bundle --no-tags
      - repo sync --force-sync

  Building_script:
      - export USE_CCACHE=1
      - export CCACHE_EXEC=/usr/bin/ccache
      - ccache -M 50G
      - export LC_ALL=C
      - export CONFIG_STATE_NOTIFIER=y
      - export SELINUX_IGNORE_NEVERALLOWS=true
      - export ALLOW_MISSING_DEPENDENCIES=true
      - source build/envsetup.sh
      - lunch lineage_RMX1851-userdebug
      - mka bacon -j$(nproc --all)

  Uploading_script:
      - curl -sL https://git.io/file-transfer | sh
      - ./transfer wet out/target/product/RMX1851/lineage*.zip
