env:
    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "CustomRom Build"
  timeout_in: 4h
  container:
      image: ubuntu-latest
      cpu: 8
      memory: 32Gb

  Prepare_the_environment_Script:
      - sudo apt-get update --fix-missing
      - sudo apt-get -y upgrade
      - sudo apt-get -y install bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libncurses5 libsdl1.2-dev libssl-dev libwxgtk3.0-gtk3-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev

  Reposync_script:
      - repo init -u https://github.com/bananadroid/android_manifest.git -b 13
      - git clone https://github.com/Think-Thought/device_realme_RMX1851 -b bananadroid ./device/realme/RMX1851
      - git clone https://github.com/Think-Thought/android_vendor_RMX1851 ./vendor/realme/RMX1851
      - repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags --optimized-fetch --prune
      - repo sync --force-sync

  Building_script:
      - export USE_CCACHE=1
      - export CCACHE_EXEC=/usr/bin/ccache
      - ccache -M 50G
      - export LC_ALL=C
      - export CONFIG_STATE_NOTIFIER=y
      - export SELINUX_IGNORE_NEVERALLOWS=true
      - export ALLOW_MISSING_DEPENDENCIES=true
      - source build/envsetup.sh
      - lunch banana_RMX1851-userdebug
      - m banana

  Uploading_script:
      - curl -sL https://git.io/file-transfer | sh
      - ./transfer wet out/target/product/RMX1851/BananaDroid*.zip
